### ISSUE TITLE
Version 2.0 Items (WIP)

### ISSUE THREAD

**Issue by davidpesce** [davidpesce/moodle-mod_tincanlaunch#189]
Here are the items on the roadmap for v2.0 of this plugin:
- [X] Remove support for Moodle prior to 3.5 and PHP prior to 7.2
- [X] Fix deprecated methods
- [X] Resolve CI build issues
- [X] Update TinCanPHP
- [X] Restore backup/moodle2
- [x] Utilize debugging feature in PHP/AMD
- [x] Add ability to send custom profile fields to xapi agentprofile
- [x] Convert PHP echo JS into AMD module(s)
- [x] Resolve cron script not using the correct actor (#181)
- [x] Refactor/rewrite completion to take into account completion verbs retrieved from the LRS (#125, #170, #163)
- [x] Optimize completion CRON (#126, #134)
- [x] Option to always launch a new attempt (#166) and launch the content directly
- [x] Make registrationid configurable - recommend removing: "tincanapi.co.uk/stateapikeys/registrations"
- [x] Address situations where a guest user is accessing this plugin (potentially disable for guests) (#16)

**Comment by davidpesce** [comment]
All fixes and features have been implemented.
